// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: monitor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sentinel_EstablishConnection_FullMethodName = "/monitor.Sentinel/EstablishConnection"
)

// SentinelClient is the client API for Sentinel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelClient interface {
	EstablishConnection(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProbeMessage, ServerCommand], error)
}

type sentinelClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelClient(cc grpc.ClientConnInterface) SentinelClient {
	return &sentinelClient{cc}
}

func (c *sentinelClient) EstablishConnection(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProbeMessage, ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sentinel_ServiceDesc.Streams[0], Sentinel_EstablishConnection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProbeMessage, ServerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sentinel_EstablishConnectionClient = grpc.BidiStreamingClient[ProbeMessage, ServerCommand]

// SentinelServer is the server API for Sentinel service.
// All implementations must embed UnimplementedSentinelServer
// for forward compatibility.
type SentinelServer interface {
	EstablishConnection(grpc.BidiStreamingServer[ProbeMessage, ServerCommand]) error
	mustEmbedUnimplementedSentinelServer()
}

// UnimplementedSentinelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelServer struct{}

func (UnimplementedSentinelServer) EstablishConnection(grpc.BidiStreamingServer[ProbeMessage, ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method EstablishConnection not implemented")
}
func (UnimplementedSentinelServer) mustEmbedUnimplementedSentinelServer() {}
func (UnimplementedSentinelServer) testEmbeddedByValue()                  {}

// UnsafeSentinelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelServer will
// result in compilation errors.
type UnsafeSentinelServer interface {
	mustEmbedUnimplementedSentinelServer()
}

func RegisterSentinelServer(s grpc.ServiceRegistrar, srv SentinelServer) {
	// If the following call panics, it indicates UnimplementedSentinelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sentinel_ServiceDesc, srv)
}

func _Sentinel_EstablishConnection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SentinelServer).EstablishConnection(&grpc.GenericServerStream[ProbeMessage, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sentinel_EstablishConnectionServer = grpc.BidiStreamingServer[ProbeMessage, ServerCommand]

// Sentinel_ServiceDesc is the grpc.ServiceDesc for Sentinel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sentinel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Sentinel",
	HandlerType: (*SentinelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishConnection",
			Handler:       _Sentinel_EstablishConnection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "monitor.proto",
}
