// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProbeMessage_Register
	//	*ProbeMessage_Result
	//	*ProbeMessage_Heartbeat
	Payload       isProbeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeMessage) Reset() {
	*x = ProbeMessage{}
	mi := &file_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeMessage) ProtoMessage() {}

func (x *ProbeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeMessage.ProtoReflect.Descriptor instead.
func (*ProbeMessage) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeMessage) GetPayload() isProbeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProbeMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ProbeMessage) GetResult() *CheckResult {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ProbeMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ProbeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isProbeMessage_Payload interface {
	isProbeMessage_Payload()
}

type ProbeMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ProbeMessage_Result struct {
	Result *CheckResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ProbeMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*ProbeMessage_Register) isProbeMessage_Payload() {}

func (*ProbeMessage_Result) isProbeMessage_Payload() {}

func (*ProbeMessage_Heartbeat) isProbeMessage_Payload() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionCode    string                 `protobuf:"bytes,1,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       int64                  `protobuf:"varint,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResult) GetCheckId() int64 {
	if x != nil {
		return x.CheckId
	}
	return 0
}

func (x *CheckResult) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CheckResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckResult) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CheckResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServerCommand struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CommandType        string                 `protobuf:"bytes,1,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	CheckId            int64                  `protobuf:"varint,2,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	CheckType          string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	Url                string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Host               string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	PostgresConnString string                 `protobuf:"bytes,6,opt,name=postgres_conn_string,json=postgresConnString,proto3" json:"postgres_conn_string,omitempty"`
	PostgresQuery      string                 `protobuf:"bytes,7,opt,name=postgres_query,json=postgresQuery,proto3" json:"postgres_query,omitempty"`
	ExpectedQueryValue string                 `protobuf:"bytes,8,opt,name=expected_query_value,json=expectedQueryValue,proto3" json:"expected_query_value,omitempty"`
	DnsHostname        string                 `protobuf:"bytes,9,opt,name=dns_hostname,json=dnsHostname,proto3" json:"dns_hostname,omitempty"`
	DnsRecordType      string                 `protobuf:"bytes,10,opt,name=dns_record_type,json=dnsRecordType,proto3" json:"dns_record_type,omitempty"`
	ExpectedDnsValue   string                 `protobuf:"bytes,11,opt,name=expected_dns_value,json=expectedDnsValue,proto3" json:"expected_dns_value,omitempty"`
	Method             string                 `protobuf:"bytes,12,opt,name=method,proto3" json:"method,omitempty"`
	TimeoutSeconds     int32                  `protobuf:"varint,13,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	JsonPath           string                 `protobuf:"bytes,14,opt,name=json_path,json=jsonPath,proto3" json:"json_path,omitempty"`
	ExpectedJsonValue  string                 `protobuf:"bytes,15,opt,name=expected_json_value,json=expectedJsonValue,proto3" json:"expected_json_value,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *ServerCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *ServerCommand) GetCheckId() int64 {
	if x != nil {
		return x.CheckId
	}
	return 0
}

func (x *ServerCommand) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *ServerCommand) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServerCommand) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerCommand) GetPostgresConnString() string {
	if x != nil {
		return x.PostgresConnString
	}
	return ""
}

func (x *ServerCommand) GetPostgresQuery() string {
	if x != nil {
		return x.PostgresQuery
	}
	return ""
}

func (x *ServerCommand) GetExpectedQueryValue() string {
	if x != nil {
		return x.ExpectedQueryValue
	}
	return ""
}

func (x *ServerCommand) GetDnsHostname() string {
	if x != nil {
		return x.DnsHostname
	}
	return ""
}

func (x *ServerCommand) GetDnsRecordType() string {
	if x != nil {
		return x.DnsRecordType
	}
	return ""
}

func (x *ServerCommand) GetExpectedDnsValue() string {
	if x != nil {
		return x.ExpectedDnsValue
	}
	return ""
}

func (x *ServerCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServerCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ServerCommand) GetJsonPath() string {
	if x != nil {
		return x.JsonPath
	}
	return ""
}

func (x *ServerCommand) GetExpectedJsonValue() string {
	if x != nil {
		return x.ExpectedJsonValue
	}
	return ""
}

var File_monitor_proto protoreflect.FileDescriptor

const file_monitor_proto_rawDesc = "" +
	"\n" +
	"\rmonitor.proto\x12\amonitor\"\xae\x01\n" +
	"\fProbeMessage\x12/\n" +
	"\bregister\x18\x01 \x01(\v2\x11.monitor.RegisterH\x00R\bregister\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x14.monitor.CheckResultH\x00R\x06result\x122\n" +
	"\theartbeat\x18\x03 \x01(\v2\x12.monitor.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"A\n" +
	"\bRegister\x12\x1f\n" +
	"\vregion_code\x18\x01 \x01(\tR\n" +
	"regionCode\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xbf\x01\n" +
	"\vCheckResult\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\x03R\acheckId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x05R\tlatencyMs\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xa4\x04\n" +
	"\rServerCommand\x12!\n" +
	"\fcommand_type\x18\x01 \x01(\tR\vcommandType\x12\x19\n" +
	"\bcheck_id\x18\x02 \x01(\x03R\acheckId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x120\n" +
	"\x14postgres_conn_string\x18\x06 \x01(\tR\x12postgresConnString\x12%\n" +
	"\x0epostgres_query\x18\a \x01(\tR\rpostgresQuery\x120\n" +
	"\x14expected_query_value\x18\b \x01(\tR\x12expectedQueryValue\x12!\n" +
	"\fdns_hostname\x18\t \x01(\tR\vdnsHostname\x12&\n" +
	"\x0fdns_record_type\x18\n" +
	" \x01(\tR\rdnsRecordType\x12,\n" +
	"\x12expected_dns_value\x18\v \x01(\tR\x10expectedDnsValue\x12\x16\n" +
	"\x06method\x18\f \x01(\tR\x06method\x12'\n" +
	"\x0ftimeout_seconds\x18\r \x01(\x05R\x0etimeoutSeconds\x12\x1b\n" +
	"\tjson_path\x18\x0e \x01(\tR\bjsonPath\x12.\n" +
	"\x13expected_json_value\x18\x0f \x01(\tR\x11expectedJsonValue2T\n" +
	"\bSentinel\x12H\n" +
	"\x13EstablishConnection\x12\x15.monitor.ProbeMessage\x1a\x16.monitor.ServerCommand(\x010\x01B\x12Z\x10gocheck/proto/pbb\x06proto3"

var (
	file_monitor_proto_rawDescOnce sync.Once
	file_monitor_proto_rawDescData []byte
)

func file_monitor_proto_rawDescGZIP() []byte {
	file_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)))
	})
	return file_monitor_proto_rawDescData
}

var file_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_monitor_proto_goTypes = []any{
	(*ProbeMessage)(nil),  // 0: monitor.ProbeMessage
	(*Register)(nil),      // 1: monitor.Register
	(*CheckResult)(nil),   // 2: monitor.CheckResult
	(*Heartbeat)(nil),     // 3: monitor.Heartbeat
	(*ServerCommand)(nil), // 4: monitor.ServerCommand
}
var file_monitor_proto_depIdxs = []int32{
	1, // 0: monitor.ProbeMessage.register:type_name -> monitor.Register
	2, // 1: monitor.ProbeMessage.result:type_name -> monitor.CheckResult
	3, // 2: monitor.ProbeMessage.heartbeat:type_name -> monitor.Heartbeat
	0, // 3: monitor.Sentinel.EstablishConnection:input_type -> monitor.ProbeMessage
	4, // 4: monitor.Sentinel.EstablishConnection:output_type -> monitor.ServerCommand
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_monitor_proto_init() }
func file_monitor_proto_init() {
	if File_monitor_proto != nil {
		return
	}
	file_monitor_proto_msgTypes[0].OneofWrappers = []any{
		(*ProbeMessage_Register)(nil),
		(*ProbeMessage_Result)(nil),
		(*ProbeMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_proto_rawDesc), len(file_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_proto_msgTypes,
	}.Build()
	File_monitor_proto = out.File
	file_monitor_proto_goTypes = nil
	file_monitor_proto_depIdxs = nil
}
