/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonitorNewRouteImport } from './routes/monitor/new'
import { Route as MonitorIdIndexRouteImport } from './routes/monitor/$id/index'
import { Route as MonitorIdEditRouteImport } from './routes/monitor/$id/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorNewRoute = MonitorNewRouteImport.update({
  id: '/monitor/new',
  path: '/monitor/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIdIndexRoute = MonitorIdIndexRouteImport.update({
  id: '/monitor/$id/',
  path: '/monitor/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIdEditRoute = MonitorIdEditRouteImport.update({
  id: '/monitor/$id/edit',
  path: '/monitor/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/monitor/new': typeof MonitorNewRoute
  '/monitor/$id/edit': typeof MonitorIdEditRoute
  '/monitor/$id': typeof MonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/monitor/new': typeof MonitorNewRoute
  '/monitor/$id/edit': typeof MonitorIdEditRoute
  '/monitor/$id': typeof MonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/monitor/new': typeof MonitorNewRoute
  '/monitor/$id/edit': typeof MonitorIdEditRoute
  '/monitor/$id/': typeof MonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/monitor/new'
    | '/monitor/$id/edit'
    | '/monitor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/monitor/new'
    | '/monitor/$id/edit'
    | '/monitor/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/monitor/new'
    | '/monitor/$id/edit'
    | '/monitor/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  MonitorNewRoute: typeof MonitorNewRoute
  MonitorIdEditRoute: typeof MonitorIdEditRoute
  MonitorIdIndexRoute: typeof MonitorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/new': {
      id: '/monitor/new'
      path: '/monitor/new'
      fullPath: '/monitor/new'
      preLoaderRoute: typeof MonitorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/$id/': {
      id: '/monitor/$id/'
      path: '/monitor/$id'
      fullPath: '/monitor/$id'
      preLoaderRoute: typeof MonitorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/$id/edit': {
      id: '/monitor/$id/edit'
      path: '/monitor/$id/edit'
      fullPath: '/monitor/$id/edit'
      preLoaderRoute: typeof MonitorIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  MonitorNewRoute: MonitorNewRoute,
  MonitorIdEditRoute: MonitorIdEditRoute,
  MonitorIdIndexRoute: MonitorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
